on:
  push:
    branches: [master]
    tags: [v*.*]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
          bundler-cache: true

      - name: Install font
        run: |
          source_zip="$(mktemp --suffix .zip)"
          curl -L "https://download.jetbrains.com/fonts/JetBrainsMono-$JETBRAINS_MONO_VERSION.zip" -o "$source_zip"
          data_home=${XDG_DATA_HOME:-$HOME/.local/share}
          mkdir -p "$data_home"
          unzip "$source_zip" 'fonts/**/*' -d "$data_home"
          fc-cache -f
          fc-list | grep 'JetBrains Mono'
        env:
          JETBRAINS_MONO_VERSION: '2.304'

      - name: Install librsvg
        run: sudo apt-get install -y librsvg2-bin

      - name: Build
        run: bundle exec ./build.rb
        env:
          OUTPUT_DIR: build
          OUTPUT_FILE: monomal.osk

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: |
            build
            monomal.osk

  push:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download
        uses: actions/download-artifact@v4
        with:
          name: build

      - name: Push
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: build
          build_dir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        uses: ncipollo/release-action@v1
        with:
          artifacts: monomal.osk
